version: '3.9'
services:
  redis:
    build:
      context: .
      dockerfile: docker/radis/Dockerfile
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  webhook:
    build:
      context: .
      dockerfile: docker/webhook/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - ORCHESTRATOR_QUEUE=orchestrator_queue
    env_file:
      - services/webhook/.env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    env_file:
      - services/orchestrator/.env
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  llm_worker:
    build:
      context: .
      dockerfile: docker/llm_worker/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - services/llm_worker/.env
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  git_worker:
    build:
      context: .
      dockerfile: docker/git_worker/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    env_file:
      - services/git_worker/.env
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
