version: '3.9'
services:
  redis:
    build:
      context: .
      dockerfile: docker/radis/Dockerfile
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  webhook:
    build:
      context: .
      dockerfile: docker/webhook/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ORCHESTRATOR_QUEUE=orchestrator_queue
    env_file:
      - services/webhook/.env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy

  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - services/orchestrator/.env
    depends_on:
      redis:
        condition: service_healthy

  llm_worker:
    build:
      context: .
      dockerfile: docker/llm_worker/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - services/llm_worker/.env
    depends_on:
      redis:
        condition: service_healthy

  git_worker:
    build:
      context: .
      dockerfile: docker/git_worker/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - services/git_worker/.env
    depends_on:
      redis:
        condition: service_healthy
